###########################################################################
- hosts: localhost
  gather_facts: false
  vars_files:
    - /etc/ansible/vars/system_copy_vars.yml
  vars:
    ansible_ssh_private_key_file: "{{ private_key }}"
  roles:
    - { role: infrastructure-deploy }
  tasks:
    - name: Refresh Inventory File
      meta: refresh_inventory
###########################################################################
- hosts: hana
  vars_files:
    - /etc/ansible/vars/system_copy_vars.yml
  vars:
    ansible_ssh_private_key_file: "{{ private_key }}"
    ansible_user: ec2-user
    ansible_become: yes
  roles:
    - { role: sap-configure-server }
###########################################################################
- hosts: hana
  vars_files:
    - /etc/ansible/vars/system_copy_vars.yml
  vars:
    ansible_ssh_private_key_file: "{{ private_key }}"
    ansible_user: root
    ansible_become: yes
  roles:
    - { role: sap-hana-preconfigure }
    - { role: sap-lg-lv-create }
    - { role: sap-filesystem-create }
    - { role: sap-mount }
    - { role: sap-copy-media }
    - { role: redhat_sap.sap_hana_deployment }
    - { role: redhat_sap.sap_s4hana_deployment }
