branches:
  only:
  - master

language: python

python:
  - '3.7'
  - '3.6'
  - '3.5'

install:
  - pip install ansible-lint
  - ansible-lint --version

script:
  - ansible-lint .

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/?branch=master
    on_failure: never